[tools]
go = "1.27.1"
gh = "2.100.0"
lfk = "v0.18.9"
atuin = "18.21.0"
kubectl = "1.36.0"
clusterctl = "1.13.4"
awscli = "2.36.43"
yq = "4.53.6"
gcloud = "569.0.0"
azure-cli = "2.90.0"
pipx = "1.16.7"
pytest = "9.1.1"
python = "3.13.7"
krew = "v0.5.0"

[tool_alias]
lfk = "github:janosmiko/lfk"
pytest = "pipx:pytest"
