[settings]
lockfile = true
auto_update = true

[tools]
oh-my-env = {
    version = "v1.4.5", # x-release-please-version
    asset_pattern = "oh-my-env-configs.tar.gz",
    minimum_release_age = "0s",
    postinstall = '''
        cp -R $MISE_TOOL_INSTALL_PATH/* ${HOME}/.config/mise/ && \
        mkdir -p ${HOME}/.local/share/zsh/completions && \
        (grep -qF 'fpath=(${HOME}/.local/share/zsh/completions $fpath)' ${HOME}/.zshrc || printf '%s\n%s\n' 'fpath=(${HOME}/.local/share/zsh/completions $fpath)' 'autoload -Uz compinit && compinit' >> ${HOME}/.zshrc)
    '''
}

[tool_alias]
oh-my-env = "github:BROngineer/oh-my-env"
