[settings]
lockfile = true
auto_update = true

[tools]
oh-my-env = {
    version = "v1.4.2", # x-release-please-version
    asset_pattern = "oh-my-env-configs.tar.gz",
    minimum_release_age = "0s",
    postinstall = "cp -R $MISE_TOOL_INSTALL_PATH/* ~/.config/mise/"
}

[tool_alias]
oh-my-env = "github:BROngineer/oh-my-env"
